apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellodocker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellodocker-deployment
  template:
    metadata:
      labels:
        app: hellodocker-deployment
    spec:
      containers:
      - name: hellodocker-deployment
        image: zaldyauw/helloDocker
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hellodocker-service
spec:
  selector:
    app: hellodocker-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
